name = "CountriesBorders"
uuid = "ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.3.2-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = "PlotlyBase"

[compat]
Artifacts = "1.9, 1"
CoordRefSystems = "0.7, 0.8, 0.9"
GeoInterface = "1"
GeoJSON = "0.8"
GeoTables = "1"
Meshes = "0.45"
PlotlyBase = "0.8"
PrecompileTools = "1"
Tables = "1"
Unitful = "1"
julia = "1.9"
